const chars=[
{id:1,name:'Konomi Tatara',anime:'Mato Seihei no Slave',element:'WIND',atk:82,def:45,hp:185,img:'images/konomi-tatara.jpg',ability:'BEAST POWER',abilityText:'+35 ATK para el resto del combate.',story:'Capitana del 1.er escuadrón. Su transformación potencia su fuerza y capacidades físicas.'},
{id:2,name:'Bell Tsukiyono',anime:'Mato Seihei no Slave',element:'LIGHT',atk:78,def:48,hp:190,img:'images/bell-tsukiyono.jpg',ability:'CANOPUS',abilityText:'+25 ATK y +20 DEF para el resto del combate.',story:'Capitana del 3.er escuadrón. Su poder se centra en una técnica de combate versátil.'},
{id:3,name:'Yakumo Ezo',anime:'Mato Seihei no Slave',element:'WIND',atk:88,def:52,hp:195,img:'images/yakumo-ezo.jpg',ability:'NIGHT STORM',abilityText:'+40 ATK para el resto del combate.',story:'Capitana del 5.º escuadrón, una combatiente de enorme poder físico y gran presencia en batalla.'},
{id:4,name:'Tenka Izumo',anime:'Mato Seihei no Slave',element:'LIGHT',atk:84,def:58,hp:205,img:'images/tenka-izumo.jpg',ability:'AME-NO-MITORI',abilityText:'+30 ATK y +15 DEF para el resto del combate.',story:'Capitana del 6.º escuadrón. Puede manipular el espacio mediante su habilidad.'},
{id:5,name:'Kyouka Uzen',anime:'Mato Seihei no Slave',element:'SHADOW',atk:86,def:55,hp:210,img:'images/kyouka-uzen.jpg',ability:'SLAVE',abilityText:'+45 ATK para el resto del combate.',story:'Capitana del 7.º escuadrón y protagonista. Su habilidad Slave potencia al aliado que combate junto a ella.'},
{id:6,name:'Varvara Pilipenko',anime:'Mato Seihei no Slave',element:'SHADOW',atk:80,def:70,hp:220,img:'images/varvara-pilipenko.jpg',ability:'PANTHEON',abilityText:'+40 DEF para el resto del combate.',story:'Capitana del 8.º escuadrón, reconocida por su extraordinaria resistencia y poder defensivo.'},
{id:7,name:'Fubuki Azuma',anime:'Mato Seihei no Slave',element:'WATER',atk:79,def:64,hp:215,img:'images/fubuki-azuma.jpg',ability:'SUNSET',abilityText:'Recupera 55 HP.',story:'Capitana del 9.º escuadrón. Su habilidad permite alterar las condiciones del combate.'},
{id:8,name:'Ren Yamashiro',anime:'Mato Seihei no Slave',element:'FIRE',atk:94,def:68,hp:225,img:'images/ren-yamashiro.jpg',ability:'ALL-ENCOMPASSING LORD OF THE COSMOS',abilityText:'+30 ATK y +25 DEF para el resto del combate.',story:'Capitana del 10.º escuadrón y comandante suprema. Es una de las combatientes más poderosas de la organización.'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let openingUrl='Opening.mp4',endingUrl='Ending.mp4',mode='opening',allies=[],enemies=[],turn=1,battleOver=false,log=[],attackerId=1,targetId=2,strategy='EQUILIBRADA';
class BattleSubject{constructor(){this.observers=[]}addObserver(o){this.observers.push(o)}notify(event){this.observers.forEach(o=>o.update(event))}}
class UiObserver{update(event){logAdd('[OBSERVER] '+event)}}
class AchievementObserver{constructor(){this.events=0}update(event){this.events++;if(this.events===3)logAdd('[ACHIEVEMENT] 🏆 Primer vínculo de batalla desbloqueado.')}}
const subject=new BattleSubject();subject.addObserver(new UiObserver());subject.addObserver(new AchievementObserver());
const clone=c=>({...c,currentHp:c.hp,currentAtk:c.atk,currentDef:c.def,ko:false,damage:0,abilityUsed:false});
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
function characterCards(){$('#characterGrid').innerHTML=chars.map(c=>`<article class="character"><img src="${c.img}" alt="${c.name}"><div class="character-body"><div class="character-top"><h3>${c.name}</h3><span class="badge">${c.element}</span></div><div class="anime">${c.anime}</div><div class="story">${c.story}</div><div class="stats"><span>ATK ${c.atk}</span><span>DEF ${c.def}</span><span>HP ${c.hp}</span></div><div class="ability-card"><strong>✨ ${c.ability}</strong><small>${c.abilityText}</small></div></div></article>`).join('')}
function optionCards(team){return chars.map(c=>`<button class="select-card" data-team="${team}" data-id="${c.id}"><img src="${c.img}" alt="${c.name}"><strong>${c.name}</strong><small>${c.element} · ATK ${c.atk} · DEF ${c.def}</small><small>✨ ${c.ability}</small></button>`).join('')}
function renderSelection(){$('#allyOptions').innerHTML=optionCards('ally');$('#enemyOptions').innerHTML=optionCards('enemy');$$('.select-card').forEach(b=>b.onclick=()=>{const id=+b.dataset.id,team=b.dataset.team;let arr=team==='ally'?allies:enemies;const other=team==='ally'?enemies:allies;if(other.some(x=>x.id===id))return;if(arr.some(x=>x.id===id))arr=arr.filter(x=>x.id!==id);else if(arr.length<3)arr=[...arr,chars.find(c=>c.id===id)];if(team==='ally')allies=arr;else enemies=arr;renderSelectionState()});renderSelectionState()}
function renderSelectionState(){$$('.select-card').forEach(b=>{const id=+b.dataset.id,team=b.dataset.team,arr=team==='ally'?allies:enemies;b.classList.toggle('selected',arr.some(c=>c.id===id));b.disabled=(team==='ally'?enemies:allies).some(c=>c.id===id)});$('#allyCount').textContent=`${allies.length}/3`,$('#enemyCount').textContent=`${enemies.length}/3`,$('#startBattle').disabled=!allies.length||!enemies.length}
function logAdd(s){log.push(s);$('#combatLog').innerHTML=log.map(x=>`<div>${x}</div>`).join('');$('#combatLog').scrollTop=999999}
function stratDamage(a,d,s){if(s==='AGRESIVA')return Math.max(1,a.currentAtk+20-Math.floor(d.currentDef/3));if(s==='DEFENSIVA')return Math.max(1,a.currentAtk-Math.floor(d.currentDef/2));return Math.max(1,a.currentAtk+Math.floor(a.currentDef/5)-Math.floor(d.currentDef/2))}
function alive(arr){return arr.filter(x=>!x.ko&&x.currentHp>0)}
function get(arr,id){return arr.find(x=>x.id===id)}
function renderBattle(){
  $('#turnTitle').textContent=`TURNO ${turn}`;
  $('#allyCards').innerHTML=allies.map(c=>card(c)).join('');$('#enemyCards').innerHTML=enemies.map(c=>card(c)).join('');
  const aa=alive(allies),ee=alive(enemies);if(!aa.some(x=>x.id===attackerId))attackerId=aa[0]?.id;if(!ee.some(x=>x.id===targetId))targetId=ee[0]?.id;
  $('#attackerSelect').innerHTML=aa.map(c=>`<option value="${c.id}">${c.name} — ${c.ability}</option>`).join('');$('#targetSelect').innerHTML=ee.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');$('#attackerSelect').value=attackerId;$('#targetSelect').value=targetId;$('#strategySelect').value=strategy;
  const a=get(allies,attackerId);$('#abilityButton').disabled=!a||a.abilityUsed;$('#abilityButton').textContent=a&&a.abilityUsed?'✨ HABILIDAD USADA':`✨ ${a?.ability||'HABILIDAD'}`;
  $('#battleStatus').textContent=battleOver?'COMBATE FINALIZADO':'Elegí atacante, objetivo y estrategia. El rival selecciona automáticamente su mejor atacante y objetivo.';
}
function card(c){const pct=Math.max(0,Math.round(c.currentHp/c.hp*100));return `<div class="combat-card ${c.ko?'ko':''}"><img src="${c.img}" alt="${c.name}"><div><h3>${c.name} · ${c.element}</h3><div class="bar"><span style="width:${pct}%"></span></div><div class="hptext">HP ${c.currentHp}/${c.hp} · ATK ${c.currentAtk} · DEF ${c.currentDef} · ${c.ko?'KO':'ACTIVA'}</div><div class="ability-line">✨ ${c.ability} ${c.abilityUsed?'· USADA':'· DISPONIBLE'}</div></div></div>`}
function beginBattle(){stopMedia();allies=allies.map(clone);enemies=enemies.map(clone);turn=1;battleOver=false;log=[];attackerId=allies[0].id;targetId=enemies[0].id;strategy='EQUILIBRADA';show('battle');logAdd(`⚔ Nuevo combate: ${allies.length} aliadas vs ${enemies.length} enemigas.`);renderBattle();save()}
function attack(){if(battleOver)return;const a=get(allies,+$('#attackerSelect').value),d=get(enemies,+$('#targetSelect').value);if(!a||!d||a.ko||d.ko)return;strategy=$('#strategySelect').value;const dmg=stratDamage(a,d,strategy);d.currentHp=Math.max(0,d.currentHp-dmg);a.damage+=dmg;subject.notify(`${d.name} recibió ${dmg} de daño. HP=${d.currentHp}`);logAdd(`⚔ TU TURNO — ${a.name} ataca a ${d.name} con ${strategy} y causa ${dmg} de daño.`);if(d.currentHp===0){d.ko=true;subject.notify(`${d.name} cambió a estado KO`);logAdd(`☠ ${d.name} desaparece del campo de batalla.`)}if(checkEnd())return;renderBattle();save();setTimeout(enemyAttack,500)}
function activateAbility(c){
  if(c.id===1){c.currentAtk+=35;return `${c.name} activa BEAST POWER: +35 ATK.`}
  if(c.id===2){c.currentAtk+=25;c.currentDef+=20;return `${c.name} activa CANOPUS: +25 ATK y +20 DEF.`}
  if(c.id===3){c.currentAtk+=40;return `${c.name} activa NIGHT STORM: +40 ATK.`}
  if(c.id===4){c.currentAtk+=30;c.currentDef+=15;return `${c.name} activa AME-NO-MITORI: +30 ATK y +15 DEF.`}
  if(c.id===5){c.currentAtk+=45;return `${c.name} activa SLAVE: +45 ATK.`}
  if(c.id===6){c.currentDef+=40;return `${c.name} activa PANTHEON: +40 DEF.`}
  if(c.id===7){const old=c.currentHp;c.currentHp=Math.min(c.hp,c.currentHp+55);return `${c.name} activa SUNSET: recupera ${c.currentHp-old} HP.`}
  c.currentAtk+=30;c.currentDef+=25;return `${c.name} activa ALL-ENCOMPASSING LORD OF THE COSMOS: +30 ATK y +25 DEF.`;
}
function useAbility(){if(battleOver)return;const a=get(allies,+$('#attackerSelect').value);if(!a||a.ko||a.abilityUsed)return;const message=activateAbility(a);a.abilityUsed=true;subject.notify(`${a.name} utilizó ${a.ability}`);logAdd('✨ '+message);renderBattle();save();setTimeout(enemyAttack,550)}
function enemyAttack(){if(battleOver)return;const e=alive(enemies).reduce((best,c)=>!best||c.currentAtk>best.currentAtk?c:best,null),t=alive(allies).reduce((best,c)=>!best||c.currentHp<best.currentHp?c:best,null);if(!e||!t)return;if(!e.abilityUsed){const message=activateAbility(e);e.abilityUsed=true;subject.notify(`${e.name} utilizó ${e.ability}`);logAdd('✨ '+message)}
const s=e.currentAtk>=120?'AGRESIVA':e.currentDef>=70?'DEFENSIVA':'EQUILIBRADA',dmg=stratDamage(e,t,s);t.currentHp=Math.max(0,t.currentHp-dmg);e.damage+=dmg;subject.notify(`${t.name} recibió ${dmg} de daño. HP=${t.currentHp}`);logAdd(`👿 TURNO ENEMIGO — ${e.name} eligió atacar a ${t.name} con ${s} y causa ${dmg} de daño.`);if(t.currentHp===0){t.ko=true;subject.notify(`${t.name} cambió a estado KO`);logAdd(`☠ ${t.name} desaparece del campo de batalla.`)}turn++;const na=alive(allies)[0],ne=alive(enemies)[0];if(na)attackerId=na.id;if(ne)targetId=ne.id;if(checkEnd())return;renderBattle();save()}
function heal(){if(battleOver)return;const a=get(allies,+$('#attackerSelect').value);if(!a||a.ko)return;a.currentHp=Math.min(a.hp,a.currentHp+35);subject.notify(`${a.name} recuperó vida. HP=${a.currentHp}`);logAdd(`💚 ${a.name} recupera 35 HP.`);if(checkEnd())return;renderBattle();save();setTimeout(enemyAttack,450)}
function checkEnd(){if(!alive(allies).length){finish(false);return true}if(!alive(enemies).length){finish(true);return true}return false}
function score(c){return Math.max(0,c.currentHp)+c.damage*2}
function finish(victory){battleOver=true;renderBattle();const title=victory?'🏆 VICTORIA':'💀 DERROTA';$('#resultTitle').textContent=title;$('#resultTitle').style.color=victory?'var(--green)':'var(--red)';$('#resultSubtitle').textContent=victory?'Todas las enemigas fueron derrotadas.':'Tu equipo fue derrotado.';$('#resultCards').innerHTML=allies.map(c=>`<div class="result-card"><img src="${c.img}" alt="${c.name}"><h3>${c.name}</h3><div>HP ${c.currentHp}/${c.hp}</div><div class="muted">Puntaje: ${score(c)}</div></div>`).join('');$('#resultScore').textContent=`PUNTAJE FINAL DEL EQUIPO: ${allies.reduce((n,c)=>n+score(c),0)}`;playMedia('ending')}
function stopMedia(){const v=$('#mediaPlayer');if(!v)return;v.pause();v.onended=null;v.removeAttribute('src');v.load()}
function playMedia(which){stopMedia();mode=which;show('mediaScreen');const v=$('#mediaPlayer'),url=which==='opening'?openingUrl:endingUrl;$('#mediaEyebrow').textContent=which==='opening'?'OPENING':'ENDING';$('#mediaTitle').textContent=which==='opening'?'MATO SEIHEI NO SLAVE — BATTLE ARENA':'BATTLE COMPLETE';v.src=url;v.currentTime=0;v.onended=()=>which==='opening'?beginBattle():show('result');v.play().catch(()=>{if(which==='opening')beginBattle();else show('result')})}
function save(){localStorage.setItem('waifuNexusWebSave',JSON.stringify({allies,enemies,turn,log,attackerId,targetId,strategy}))}
function load(){try{const s=JSON.parse(localStorage.getItem('waifuNexusWebSave'));return s&&s.allies?.length&&s.enemies?.length?s:null}catch{return null}}
$('#playButton').onclick=()=>show('selection');$('#continueButton').onclick=()=>{const s=load();if(!s)return;allies=s.allies;enemies=s.enemies;turn=s.turn;log=s.log||[];attackerId=s.attackerId;targetId=s.targetId;strategy=s.strategy||'EQUILIBRADA';battleOver=false;show('battle');renderBattle();};$('#startBattle').onclick=()=>playMedia('opening');$('#skipMedia').onclick=()=>{stopMedia();if(mode==='opening')beginBattle();else show('result')};$('#attackButton').onclick=attack;$('#abilityButton').onclick=useAbility;$('#healButton').onclick=heal;$('#saveButton').onclick=()=>{save();$('#battleStatus').textContent='✓ Combate guardado en este navegador.'};$('#attackerSelect').onchange=e=>{attackerId=+e.target.value;renderBattle()};$('#targetSelect').onchange=e=>targetId=+e.target.value;$('#strategySelect').onchange=e=>strategy=e.target.value;$('#resultHome').onclick=()=>{localStorage.removeItem('waifuNexusWebSave');allies=[];enemies=[];show('landing')};$$('[data-home]').forEach(b=>b.onclick=()=>show('landing'));
characterCards();renderSelection();if(load())$('#continueButton').hidden=false;
